### ISSUE TITLE
permission denied .kweb

### ISSUE THREAD

**Issue by f31n** [Kopano-dev/kopano-docker#12]
when running docker compose on a freshly installed debian server (with actual docker version) web cannot startup

it always gets the error:

chown: /.kweb/locks: Permission denied
chown: /.kweb/acme: Permission denied

I created in the same folder of docker-compose a folder web and gave that one 777 permission - to try, without any success.

any ideas what i'm doing wrong?

**Comment by fbartels** [comment]
Hi @f31n,

please provide the data from https://github.com/kopano-dev/kopano-docker#troubleshooting

**Comment by f31n** [comment]
I'm trying to run 
https://github.com/Kopano-dev/kopano-docker/tree/master/examples/meet
Running Kopano Meet without Kopano (with only the LDAP backend), with the default setup.sh

after cloning the folder I ran setup.sh provinding a valid DNS name and added a valid email for letsencrypt leaving everything else at default.
after that I edited the .env and added my turn user and password.

and i didn't user "docker-compose up", but "docker-compose up -d"

**Comment by fbartels** [comment]
Hi @f31n,

your last update only partly answers my question. The output of `docker-compose config` can be quite helpful to reproduce issues (I can then run a setup that is configured in the exact same way your environment is). But knowing you are running the meet example also provided me with the required clue.

The problem should be resolved with the changes from https://github.com/zokradonh/kopano-docker/pull/375.

Please confirm if that is the case for you.

**Comment by f31n** [comment]
thank you very much, and sorry for the troubles. next time I'll definitely provide you with the docker-compose.yml // config!

yes, its working like a charm now!

**Comment by fbartels** [comment]
No problem
