### ISSUE TITLE
kopano_webapp healthcheck always failing on /var/lib/kopano-webapp/tmp

### ISSUE THREAD

**Issue by deatheibon** [Kopano-dev/kopano-docker#26]
healthcheck (goss -g /goss/goss.yaml validate) is always failing on  /var/lib/kopano-webapp/tmp complaining problems with size of directory: 

.....F............

Failures/Skipped:

File: /var/lib/kopano-webapp/tmp: size:
Expected
    <int>: 40
to equal
    <int>: 4096

Total Duration: 0.006s
Count: 18, Failed: 1, Skipped: 0

**To Reproduce**

1. docker exec -ti kopano_webapp bash 
2. goss -g /goss/goss.yaml v
4. .....F............

Failures/Skipped:

File: /var/lib/kopano-webapp/tmp: size:
Expected
    <int>: 40
to equal
    <int>: 4096

Total Duration: 0.006s
Count: 18, Failed: 1, Skipped: 0

ls -al /var/lib/kopano-webapp/
total 0
drwxr-xr-x 1 root     root      6 May  4  2021 .
drwxr-xr-x 1 root     root     14 Mar 21 22:04 ..
drwxr-xr-x 2 www-data www-data 40 Mar 21 22:04 tmp

**Expected behavior**

.................

Total Duration: 0.005s
Count: 17, Failed: 0, Skipped: 0

**Additional context**
i could temporary fix it with removing the "size: 4096" line from the /var/lib/kopano-webapp/tmp block and mapping the file inside the conatiner: 

  /var/lib/kopano-webapp/tmp:
    exists: true
    mode: "0755"
    owner: www-data
    group: www-data
    filetype: directory
    contains: []

i tried also to create tmpfs mounted to /var/lib/kopano-webapp/tmp with diffrent sizes with no success.

**Comment by fbartels** [comment]
I guess this could have gotten broken in https://github.com/Kopano-dev/kopano-docker/pull/10/files.

The size check is not really that important, I would recommend to just remove it. Do you want to open a pull request with it?

**Comment by deatheibon** [comment]
Yes i want to open pull request.

**Comment by fbartels** [comment]
Let me know if you need any help with that @deatheibon
